name: Fetch latest blog post

on:
  push:
    branches: [ "master" ]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install curl pipx jq
          pipx install yq jinja2-cli

      - name: Fetch latest blog post from RSS feed
        run: |
          item="$(curl -s https://joaocosta.dev/rss | xq -r '.rss.channel.item[0]')"
          echo $item
          parsed_item="$(echo "$item" | jq -r '{title: .title, summary: .description, url: .link}')"
          echo "$parsed_item" | jinja2 README.j2 --format=json >README.md
          
      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          add: 'README.md'
          default_author: github_actions
          message: 'Update latest blog post'
          pathspec_error_handling: exitImmediately
